8 post comment
Daniel17971/fe-project-nc-games pull request #5
Opened 2023-04-18 14:26 UTC by Daniel17971

2023-04-18 15:03 UTC, callumu21 requested changes
A good start, Daniel, but some changes will need to be made before this can be approved:

1. Posting a comment shouldn't need a new route. If you're dead-set on this functionality, that's cool, but it would be much better to have the add form component appear on the individual review page alongside the other comments and review. This is partly for better user experience (if I'm writing a comment, I likely want to see the review and other comments), but also prevents the creation of redundant routes.
2. You should also add a logged-in user, rather than asking someone to supply a username. This can either be hardcoded in state for demo purposes, or you can have a log in screen or button to handle this instead.
3. You need some validation on the text input field for a comment as currently empty comments can be posted.
4. You should also add a reset to the form fields on a successful submission, just in case they want to add more than one comment.
5. You should also consider a way of preventing multiple post attempts being made. Currently, a user can press submit multiple times before the first one is complete. State would be a good way of handling this.

Finally, I would consider looking at some of your styling, just to make sure that presentation is okay on a smaller screen. Currently the form component becomes quite compressed on smaller screens.

Once you've implemented the above, please resubmit this PR and we'll take another look 👍

2023-04-18 15:03 UTC, callumu21 commented on src/App.js
> +        <Route path="/reviews/:review_id/comments" element={<PostComment />} />
I wouldn't have this as a new route. Adding a comment should be a part of the individual review screen, both for user experience and to save you having redundant endpoints

2023-04-18 15:03 UTC, callumu21 commented on src/components/PostComment.jsx
> +          setErr("That User doesn't exsist!!!");
Just be careful of the spelling mistake here - 'That user doesn't exist!!!'. There are also other issues that could happen here, such as an unsuccessful request due to network issues, so consider handling this here as well.

2023-04-18 15:03 UTC, callumu21 commented on src/components/PostComment.jsx
> +        <label htmlFor="username-input">Username: </label>
Users shouldn't have to put in their username - this should instead be handled by having a logged in user across the site. This is also relevant for this as a portfolio piece, as a prospective employer isn't going to be know what valid usernames they can enter to see if this is working

2023-04-18 15:03 UTC, callumu21 commented on src/components/PostComment.jsx
> +  const handleSubmit = (event) => {
You will need some validation here that a user has actually inputted a comment. Currently, an empty comment can be posted.

2023-04-19 10:49 UTC, HeatherEver reviewed
This is good work Daniel but there's still a couple of things to look at here... 
- when i log in as a user there's no kind of confirmation to say it's been successful, which as a user would be nice
- when i post a comment both messages of 'you are not logged in' and 'post successful' appear on the screen (see below)
- the new comment also goes to the back of the comments which is good when there's only one page but when there's multiple pages my comment goes to the very back which isn't very user friendly 
- although the CSS isn't too important right now, it's worth noting that when the screen is changed size some things start to get a bit weird (see below) 
<img width="266" alt="Screenshot 2023-04-19 at 11 38 50" src="https://user-images.githubusercontent.
<img width="1045" alt="Screenshot 2
<img width="1508" alt="Screenshot 2023-04-19 at 11 28 47" src="https://user-images.githubusercontent.com/79215884/233052496-8e66a473-317b-4cc3-875e-b2957c145804.png">
023-04-19 at 11 28 58" src="https://user-images.githubusercontent.com/79215884/233052483-404d9a50-7f07-469e-aca5-79cd3a1d3903.png">
com/79215884/233052465-46aa1785-170d-403d-8825-96a9dd1528cd.png">

2023-04-19 10:49 UTC, HeatherEver commented on src/components/PostComment.jsx
> +          setErr("Your not loged in!");
little spelling mistake here in 'logged'

2023-04-19 10:49 UTC, HeatherEver commented on src/components/PostComment.jsx
> +          console.log("here");
remove console logs

2023-04-19 12:48 UTC, merged